
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        env:
          - name: HELLO_MESSAGE
            valueFrom:
              secretKeyRef:
                name: helloweb
                key: message
        image: harbor.csvcdev.vpc.arvato-systems.de/k8s-workshop/hello-php:1.0
        ports:
        - containerPort: 80
