apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: harbor.csvcdev.vpc.arvato-systems.de/k8s-workshop/gb-nginx:latest

