apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-phpfpm
spec:
  selector:
    matchLabels:
        app: guestbook
        tier: phpfpm
  template:
    metadata:
      labels:
        app: guestbook
        tier: phpfpm
    spec:
      containers:
      - name: phpfpm
        image: harbor.csvcdev.vpc.arvato-systems.de/k8s-workshop/gb-phpfpm:v8
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 9000
          name: phpfpm
