apiVersion: v1
kind: Service
metadata:
  name: gb
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: guestbook
    tier: frontend