apiVersion: v1
kind: Service
metadata:
  name: gb-phpfpm
  labels:
    app: guestbook
    tier: phpfpm
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
  - port: 9000
  selector:
    app: guestbook
    tier: phpfpm