apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc-pod
spec:
  volumes:
    - name: static-www
      persistentVolumeClaim:
        claimName: static-www-claim
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: static-www