apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-www
  labels:
    type: local
    pv: static-www
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/www/html-static"
    type: DirectoryOrCreate