apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-www-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: static-www