FROM bitnami/nginx:1.20

ADD controllers.js /app/controllers.js
ADD angular.min.js /app/angular.min.js
ADD ui-bootstrap-tpls.js /app/ui-bootstrap-tpls.js
ADD bootstrap.min.css /app/bootstrap.min.css
ADD index.html /app/index.html
