apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
      - name: init-redis
        image: harbor.csvcdev.vpc.arvato-systems.de/k8s-workshop/redis:6.0
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate redis server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          # Copy appropriate conf.d files from config-map to emptyDir.
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/master.conf /etc/redis.conf
          else
            cp /mnt/config-map/follower.conf /etc/redis.conf
          fi
        volumeMounts:
        - name: conf
          mountPath: /etc
          subPath: redis.conf
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - name: redis
        image: harbor.csvcdev.vpc.arvato-systems.de/k8s-workshop/redis:6.0
        command:
          - "redis-server"
          - "/etc/redis.conf"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: conf
          mountPath: /etc
          subPath: redis.conf
        - name: redis-data
          mountPath: /data
      volumes:
        - name: conf
          emptyDir: {}
        - name: redis-data
          emptyDir: {}
        - name: config-map
          configMap:
            name: redis
                      

