apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl-list
  name: kubectl-list
  namespace: rbac
spec:
  containers:
  - image: harbor.csvcdev.vpc.arvato-systems.de/k8s-workshop/kubectl:1.20.10
    imagePullPolicy: IfNotPresent
    name: kubectl
    command: [ "sleep","3600" ]
  restartPolicy: Always
  serviceAccount: list
  serviceAccountName: list