apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: busybox
  namespace: k8s-workshop
spec:
  imagePullSecrets:
    - name: myregistrykey
  containers:
  - image: harbor2.csvcdev.vpc.arvato-systems.de/k8s-workshop-private/busybox:latest
    imagePullPolicy: Always
    name: busybox
    command:
      - "sleep"
      - "300"
  restartPolicy: Always
