apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list
  namespace: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list
subjects:
- kind: ServiceAccount
  name: list
  namespace: rbac
